language: node_js
node_js:
  - "10"
install:
  - npm install
cache: npm
jobs:
  include:
    - stage: tests
      script: npm run tests
deploy:
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"
  on:
    condition: tag IS present
stages:
  - name: tests
    if: type IN (pull_request, push) AND tag IS blank
